### ISSUE TITLE
connection-pool-0.1.2.0 doesn't compile

### ISSUE THREAD

**Issue by peti** [trskop/connection-pool#1]
Citing from http://hydra.cryp.to/build/1183547/nixlog/3/raw:

```
src/Data/ConnectionPool/Internal/Streaming.hs:126:29:
    Constructor ‘ClientSettings’ should have 4 arguments, but has been given 3
    In the pattern: ClientSettings port host addrFamily
    In an equation for ‘acquireTcpClientConnection’:
        acquireTcpClientConnection (ClientSettings port host addrFamily)
          = getSocketFamilyTCP host port addrFamily
```

**Comment by trskop** [comment]
Package streaming-commons changed some of its data types and code of this library had to be updated accordingly, but those new fields aren't used. Plan is to include that functionality in to future release.

Release with this fix is available on Hackage: http://hackage.haskell.org/package/connection-pool-0.1.2.1
